# Generated by Django 3.1.3 on 2020-11-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201105_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datacompleted',
            new_name='datecompleted',
        ),
    ]
